### ISSUE TITLE
error when search string contains brackets

### ISSUE THREAD

**Issue by idej** [krt/redis-asm#1]
When search string contains brackets − got an error `Redis::CommandError: ERR Error running script`.

```
> asm.search(MY_KEY, '(searchworld)')
#= Redis::CommandError: ERR Error running script (call to f_9655e89cb9df8522d0adde4c2f1979574f1d83f8): @user_script:120: user_script:120: unfinished capture
```

**Comment by krt** [comment]
@idej Thanks for your report. I will fix it soon, please keep in touch.

**Comment by krt** [comment]
@idej This issue has been fixed. You can use v0.2.0 and works correctly.
